<a href="https://colab.research.google.com/github/Gadinggemintang/PBO_4423/blob/main/Preprocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [185]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [205]:
dataset = pd.read_csv('dataa.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [206]:
print(x)

[['boja' 66.0 3000.0]
 ['mijen' 23.0 nan]
 ['krapyak' 71.0 43000.0]
 ['ngaliyan' nan 30000.0]
 ['jrakah' 21.0 21000.0]
 ['majapahit' 45.0 2100.0]
 ['kalibanteng' 67.0 2300.0]]


In [207]:
print(y)

['ya' 'tidak' 'ya' 'tidak' 'ya' 'ya' 'tidak']


In [208]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [209]:
print(x)

[['boja' 66.0 3000.0]
 ['mijen' 23.0 16900.0]
 ['krapyak' 71.0 43000.0]
 ['ngaliyan' 48.833333333333336 30000.0]
 ['jrakah' 21.0 21000.0]
 ['majapahit' 45.0 2100.0]
 ['kalibanteng' 67.0 2300.0]]


In [210]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
x = np.array(ct.fit_transform(x))

In [211]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 66.0 3000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 23.0 16900.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 71.0 43000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 48.833333333333336 30000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 21.0 21000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 45.0 2100.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 67.0 2300.0]]


In [213]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [214]:
print(y)

[1 0 1 0 1 1 0]


In [215]:
 from sklearn.model_selection import train_test_split
 x_tarin, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [216]:
print(x_train)

[[1.0 0.0 0.0 -0.7071067811865476 1.4142135623730951 -0.6317772292155608
  0.07412493166610994]
 [1.0 0.0 1.0 -0.7071067811865476 -0.7071067811865476 -0.779850017312958
  -1.260123838323872]
 [1.0 0.0 0.0 1.4142135623730951 -0.7071067811865476 1.411627246528519
  1.185998906657762]]


In [217]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 67.0 2300.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 71.0 43000.0]]


In [218]:
print(y_train)

[0 1 1 0 1]


In [219]:
print(y_test)

[0 1]


In [220]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

ValueError: ignored

In [221]:
print(x_train)

[[1.0 0.0 0.0 -0.7071067811865476 1.4142135623730951 -0.6317772292155608
  0.07412493166610994]
 [1.0 0.0 1.0 -0.7071067811865476 -0.7071067811865476 -0.779850017312958
  -1.260123838323872]
 [1.0 0.0 0.0 1.4142135623730951 -0.7071067811865476 1.411627246528519
  1.185998906657762]]
